services:
  backend:
    build: ./backend
    image: projectboard-backend
    restart: unless-stopped
    environment:
      - DB_PATH=/data/projects.db
    volumes:
      - db:/data
    expose:
      - "8000"

  web:
    build: ./frontend
    image: projectboard-web
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  db:
